### ISSUE TITLE
Upgrade Planner and Subteranean causing crashes now

### ISSUE THREAD

**Issue by jarquafelmu** [Klonan/upgrade-planner#2]
Started yesterday or 0.16.26. When upgrade planner attempts to upgrade a section that contains a subterranean belt part the game crashes with the following error:

![upgrade planner](https://user-images.githubusercontent.com/5807272/36764926-23f4433a-1bec-11e8-8edf-a8bf10ddf5ff.PNG)

Here is a link to the issue in their repo: [Issue 2](https://github.com/Bilka2/Subterrain/issues/2)

**Comment by Bilka2** [comment]
Fixed from my side.
