### ISSUE TITLE
Desync when clicking UI button

### ISSUE THREAD

**Issue by ChurchOrganist** [Klonan/upgrade-planner#3]
I've just experienced a desync on my server immediately after opening the planner interface.

This has happened before, but I didn't report it in case it was a one off.

I have the following mods active and running.....
Advanced_Radar_0.16.2
DeadlockCrating_1.1.4
DeadlockLoaders_1.2.7
DeadlockStacking_1.4.8
FNEI_0.1.5
LightedPolesPlus_1.1.3
miniloader_1.5.16
PickerExtended_3.0.3
PickerTweaks_1.0.2
pycoalprocessing_1.0.2
pyfusionenergy_1.0.1
pyindustry_1.0.6
rso-mod_3.5.10
Tiny_Start_0.16.0
upgrade-planner_1.5.2

On restarting I repeated clicking the UI button standing exactly in the same place as I was when the desync happened.

I hope that gives you enough information to track down the problem. 
I'm currently uploading the Desync report to my Google Drive and will post the link here as soon as it has finished.

**Comment by Klonan** [comment]
With so many mods, many of which can hook into the button press function, I am likely to believe this is another mod causing the issue

I haven't received any other reports of any desync from any players,
But I will keep an eye out if more people start reporting the issue

**Comment by ChurchOrganist** [comment]
Thanks for replying so quickly.

Here's the link to the desync report.......
https://drive.google.com/file/d/1aGCBjLcslQBzxzU48iva56gL3qNTJEu_/view?usp=sharing
