### ISSUE TITLE
Allow deleting of upgrade planner items in inventory

### ISSUE THREAD

**Issue by VenatusSimpleX** [Klonan/upgrade-planner#5]
Based on this [post](https://forums.factorio.com/viewtopic.php?p=371397#p371397).

I think it would be real useful if an option is added to remove the items in inventory, since if we can't do so then there is a chance our inventories will get cluttered and fileed with upgrade planners by mistake.

**Comment by ChildishGiant** [comment]
Could you put this fork on the mod portal?

**Comment by VenatusSimpleX** [comment]
@ChildishGiant Not sure if I'm allowed to, since this is not even my mod

**Comment by ChildishGiant** [comment]
I was just thinking since the owner seems to not be implementing your fork. There's no license in this repo so I don't think you'd be allowed :(
